import localFont from "next/font/local";
import { ThemeProvider, useDarkTheme } from "./context/DarkTheme";
import "./globals.css";
import Container from "./components/container";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Story Stream",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
      <html lang="en">
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
          precedence="default"
          rel="stylesheet"
        />

        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Container>{children}</Container>
        </body>
      </html>
    </ThemeProvider>
  );
}
