import localFont from "next/font/local";
import { ThemeProvider, useDarkTheme } from "./context/DarkTheme";
import "./globals.css";
import Container from "./components/container";
import Script from "next/script";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Story Stream",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased  bg-white dark:bg-gray-800`}
        >
          <Container>{children}</Container>
        </body>
      </html>
    </ThemeProvider>
  );
}
